spring.application.name=demo

jwk.domain=http://localhost:8082/realms/pitstop
jwk.domain-keys=http://localhost:8082/realms/pitstop/protocol/openid-connect/certs
jwk.client-id=angular-app
keycloak.baseUrl=http://keycloak:8080
keycloak.realm=pitstop
keycloak.clientId=pitstop-client
keycloak.clientSecret=ucC1eTDmVdEYmDZgSW0G1n4FXL20j1Wl
rdw.domain=https://opendata.rdw.nl
mapbox.domain=https://api.mapbox.com
aaa.domain=https://api.f681e3263e1d4d0fb6669e61efcfedd1.flux.host