spring.application.name=demo

default-admins=pitstop-admin

jwk.domain=https://track-rejoice-dev-7kxie6.us1.zitadel.cloud
jwk.domain-keys=https://track-rejoice-dev-7kxie6.us1.zitadel.cloud/oauth/v2/keys

rdw.domain=https://opendata.rdw.nl
mapbox.domain=https://api.mapbox.com
aaa.domain=https://api.f681e3263e1d4d0fb6669e61efcfedd1.flux.host