spring.application.name=demo

default-admins=admin@pitstop.com

jwk.domain=http://localhost:8082/realms/pitstop
jwk.domain-keys=http://localhost:8082/realms/pitstop/protocol/openid-connect/certs
jwk.client-id=angular-app
rdw.domain=https://opendata.rdw.nl
mapbox.domain=https://api.mapbox.com
aaa.domain=https://api.f681e3263e1d4d0fb6669e61efcfedd1.flux.host